export const BAOCAOBANHANG_LIST_REQUEST = "BAOCAOBANHANG_LIST_REQUEST";
export const BAOCAOBANHANG_LIST_SUCCESS = "BAOCAOBANHANG_LIST_SUCCESS";
export const BAOCAOBANHANG_LIST_FAIL = "BAOCAOBANHANG_LIST_FAIL";

export const BAOCAOBANHANG_DETAIL_REQUEST = "BAOCAOBANHANG_DETAIL_REQUEST";
export const BAOCAOBANHANG_DETAIL_SUCCESS = "BAOCAOBANHANG_DETAIL_SUCCESS";
export const BAOCAOBANHANG_DETAIL_FAIL = "BAOCAOBANHANG_DETAIL_FAIL";

export const BAOCAOBANHANG_CREATE_REQUEST = "BAOCAOBANHANG_CREATE_REQUEST";
export const BAOCAOBANHANG_CREATE_SUCCESS = "BAOCAOBANHANG_CREATE_SUCCESS";
export const BAOCAOBANHANG_CREATE_FAIL = "BAOCAOBANHANG_CREATE_FAIL";
