export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";

export const CHAT_DETAIL_REQUEST = "CHAT_DETAIL_REQUEST";
export const CHAT_DETAIL_SUCCESS = "CHAT_DETAIL_SUCCESS";
export const CHAT_DETAIL_FAIL = "CHAT_DETAIL_FAIL";

export const CHAT_DETAIL_LIST_REQUEST = "CHAT_DETAIL_LIST_REQUEST";
export const CHAT_DETAIL_LIST_SUCCESS = "CHAT_DETAIL_LIST_SUCCESS";
export const CHAT_DETAIL_LIST_FAIL = "CHAT_DETAIL_LIST_FAIL";

export const CHAT_DELETE_REQUEST = "CHAT_DELETE_REQUEST";
export const CHAT_DELETE_SUCCESS = "CHAT_DELETE_SUCCESS";
export const CHAT_DELETE_FAIL = "CHAT_DELETE_FAIL";

export const CHAT_CREATE_REQUEST = "CHAT_CREATE_REQUEST";
export const CHAT_CREATE_SUCCESS = "CHAT_CREATE_SUCCESS";
export const CHAT_CREATE_FAIL = "CHAT_CREATE_FAIL";

export const CHAT_UPDATE_REQUEST = "CHAT_UPDATE_REQUEST";
export const CHAT_UPDATE_SUCCESS = "CHAT_UPDATE_SUCCESS";
export const CHAT_UPDATE_FAIL = "CHAT_UPDATE_FAIL";
