export const CHUCVU_LIST_REQUEST = "CHUCVU_LIST_REQUEST";
export const CHUCVU_LIST_SUCCESS = "CHUCVU_LIST_SUCCESS";
export const CHUCVU_LIST_FAIL = "CHUCVU_LIST_FAIL";

export const CHUCVU_PERMISSIONS_REQUEST = "CHUCVU_PERMISSIONS_REQUEST";
export const CHUCVU_PERMISSIONS_SUCCESS = "CHUCVU_PERMISSIONS_SUCCESS";
export const CHUCVU_PERMISSIONS_FAIL = "CHUCVU_PERMISSIONS_FAIL";
export const DELETE_CHUCVU_PERMISSIONS = "DELETE_CHUCVU_PERMISSIONS";

export const CHUCVU_ALL_PERMISSIONS_REQUEST = "CHUCVU_ALL_PERMISSIONS_REQUEST";
export const CHUCVU_ALL_PERMISSIONS_SUCCESS = "CHUCVU_ALL_PERMISSIONS_SUCCESS";
export const CHUCVU_ALL_PERMISSIONS_FAIL = "CHUCVU_ALL_PERMISSIONS_FAIL";

export const CHUCVU_ADD_PERMISSIONS_REQUEST = "CHUCVU_ADD_PERMISSIONS_REQUEST";
export const CHUCVU_ADD_PERMISSIONS_SUCCESS = "CHUCVU_ADD_PERMISSIONS_SUCCESS";
export const CHUCVU_ADD_PERMISSIONS_FAIL = "CHUCVU_ADD_PERMISSIONS_FAIL";
