export const CHUCVU_LIST_REQUEST = "CHUCVU_LIST_REQUEST";
export const CHUCVU_LIST_SUCCESS = "CHUCVU_LIST_SUCCESS";
export const CHUCVU_LIST_FAIL = "CHUCVU_LIST_FAIL";

export const CHUCVU_DELETE_REQUEST = "CHUCVU_DELETE_REQUEST";
export const CHUCVU_DELETE_SUCCESS = "CHUCVU_DELETE_SUCCESS";
export const CHUCVU_DELETE_FAIL = "CHUCVU_DELETE_FAIL";

export const CHUCVU_CREATE_REQUEST = "CHUCVU_CREATE_REQUEST";
export const CHUCVU_CREATE_SUCCESS = "CHUCVU_CREATE_SUCCESS";
export const CHUCVU_CREATE_FAIL = "CHUCVU_CREATE_FAIL";

export const CHUCVU_UPDATE_REQUEST = "CHUCVU_UPDATE_REQUEST";
export const CHUCVU_UPDATE_SUCCESS = "CHUCVU_UPDATE_SUCCESS";
export const CHUCVU_UPDATE_FAIL = "CHUCVU_UPDATE_FAIL";

export const CHUCVU_PERMISSIONS_REQUEST = "CHUCVU_PERMISSIONS_REQUEST";
export const CHUCVU_PERMISSIONS_SUCCESS = "CHUCVU_PERMISSIONS_SUCCESS";
export const CHUCVU_PERMISSIONS_FAIL = "CHUCVU_PERMISSIONS_FAIL";

export const CHUCVU_ALL_PERMISSIONS_REQUEST = "CHUCVU_ALL_PERMISSIONS_REQUEST";
export const CHUCVU_ALL_PERMISSIONS_SUCCESS = "CHUCVU_ALL_PERMISSIONS_SUCCESS";
export const CHUCVU_ALL_PERMISSIONS_FAIL = "CHUCVU_ALL_PERMISSIONS_FAIL";

export const CHUCVU_ADD_PERMISSIONS_REQUEST = "CHUCVU_ADD_PERMISSIONS_REQUEST";
export const CHUCVU_ADD_PERMISSIONS_SUCCESS = "CHUCVU_ADD_PERMISSIONS_SUCCESS";
export const CHUCVU_ADD_PERMISSIONS_FAIL = "CHUCVU_ADD_PERMISSIONS_FAIL";