export const GIAY_LIST_REQUEST = "GIAY_LIST_REQUEST";
export const GIAY_LIST_SUCCESS = "GIAY_LIST_SUCCESS";
export const GIAY_LIST_FAIL = "GIAY_LIST_FAIL";

export const GIAY_REQUEST = "GIAY_REQUEST";
export const GIAY_SUCCESS = "GIAY_SUCCESS";
export const GIAY_FAIL = "GIAY_FAIL";

export const GIAY_DETAIL_REQUEST = "GIAY_DETAIL_REQUEST";
export const GIAY_DETAIL_SUCCESS = "GIAY_DETAIL_SUCCESS";
export const GIAY_DETAIL_FAIL = "GIAY_DETAIL_FAIL";

export const GIAY_SIZE_LIST_REQUEST = "GIAY_SIZE_LIST_REQUEST";
export const GIAY_SIZE_LIST_SUCCESS = "GIAY_SIZE_LIST_SUCESS";
export const GIAY_SIZE_LIST_FAIL = "GIAY_SIZE_LIST_FAIL";

export const GIAY_DELETE_REQUEST = "GIAY_DELETE_REQUEST";
export const GIAY_DELETE_SUCCESS = "GIAY_DELETE_SUCCESS";
export const GIAY_DELETE_FAIL = "GIAY_DELETE_FAIL";

export const GIAY_CREATE_REQUEST = "GIAY_CREATE_REQUEST";
export const GIAY_CREATE_SUCCESS = "GIAY_CREATE_SUCCESS";
export const GIAY_CREATE_FAIL = "GIAY_CREATE_FAIL";
export const GIAY_CREATE_RESET = "GIAY_CREATE_RESET";

export const GIAY_UPDATE_REQUEST = "GIAY_UPDATE_REQUEST";
export const GIAY_UPDATE_SUCCESS = "GIAY_UPDATE_SUCCESS";
export const GIAY_UPDATE_FAIL = "GIAY_UPDATE_FAIL";

export const SET_PRODUCTS_REQUEST = "SET_PRODUCTS_REQUEST";
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_FAIL = "SET_PRODUCTS_FAIL";
