export const GIOHANG_LIST_REQUEST = "GIOHANG_LIST_REQUEST";
export const GIOHANG_LIST_SUCCESS = "GIOHANG_LIST_SUCCESS";
export const GIOHANG_LIST_FAIL = "GIOHANG_LIST_FAIL";

export const GIOHANG_DETAIL_REQUEST = "GIOHANG_DETAIL_REQUEST";
export const GIOHANG_DETAIL_SUCCESS = "GIOHANG_DETAIL_SUCCESS";
export const GIOHANG_DETAIL_FAIL = "GIOHANG_DETAIL_FAIL";

export const GIOHANG_DELETE_REQUEST = "GIOHANG_DELETE_REQUEST";
export const GIOHANG_DELETE_SUCCESS = "GIOHANG_DELETE_SUCCESS";
export const GIOHANG_DELETE_FAIL = "GIOHANG_DELETE_FAIL";

export const GIOHANG_CREATE_REQUEST = "GIOHANG_CREATE_REQUEST";
export const GIOHANG_CREATE_SUCCESS = "GIOHANG_CREATE_SUCCESS";
export const GIOHANG_CREATE_FAIL = "GIOHANG_CREATE_FAIL";

export const GIOHANG_UPDATE_REQUEST = "GIOHANG_UPDATE_REQUEST";
export const GIOHANG_UPDATE_SUCCESS = "GIOHANG_UPDATE_SUCCESS";
export const GIOHANG_UPDATE_FAIL = "GIOHANG_UPDATE_FAIL";

export const GIOHANG_ADD_ITEM = "GIOHANG_ADD_ITEM";
export const GIOHANG_REMOVE_ITEM = "GIOHANG_REMOVE_ITEM";
