export const HANGSANXUAT_LIST_REQUEST = "HANGSANXUAT_LIST_REQUEST";
export const HANGSANXUAT_LIST_SUCCESS = "HANGSANXUAT_LIST_SUCCESS";
export const HANGSANXUAT_LIST_FAIL = "HANGSANXUAT_LIST_FAIL";

export const HANGSANXUAT_DETAIL_REQUEST = "HANGSANXUAT_DETAIL_REQUEST";
export const HANGSANXUAT_DETAIL_SUCCESS = "HANGSANXUAT_DETAIL_SUCCESS";
export const HANGSANXUAT_DETAIL_FAIL = "HANGSANXUAT_DETAIL_FAIL";

export const HANGSANXUAT_SIZE_LIST_REQUEST = "HANGSANXUAT_SIZE_LIST_REQUEST";
export const HANGSANXUAT_SIZE_LIST_SUCESS = "HANGSANXUAT_SIZE_LIST_SUCESS";
export const HANGSANXUAT_SIZE_LIST_FAIL = "HANGSANXUAT_SIZE_LIST_FAIL";

export const HANGSANXUAT_DELETE_REQUEST = "HANGSANXUAT_DELETE_REQUEST";
export const HANGSANXUAT_DELETE_SUCCESS = "HANGSANXUAT_DELETE_SUCCESS";
export const HANGSANXUAT_DELETE_FAIL = "HANGSANXUAT_DELETE_FAIL";

export const HANGSANXUAT_CREATE_REQUEST = "HANGSANXUAT_CREATE_REQUEST";
export const HANGSANXUAT_CREATE_SUCCESS = "HANGSANXUAT_CREATE_SUCCESS";
export const HANGSANXUAT_CREATE_FAIL = "HANGSANXUAT_CREATE_FAIL";

export const HANGSANXUAT_UPDATE_REQUEST = "HANGSANXUAT_UPDATE_REQUEST";
export const HANGSANXUAT_UPDATE_SUCCESS = "HANGSANXUAT_UPDATE_SUCCESS";
export const HANGSANXUAT_UPDATE_FAIL = "HANGSANXUAT_UPDATE_FAIL";
