export const MAU_LIST_REQUEST = "MAU_LIST_REQUEST";
export const MAU_LIST_SUCCESS = "MAU_LIST_SUCCESS";
export const MAU_LIST_FAIL = "MAU_LIST_FAIL";

export const MAU_DETAIL_REQUEST = "MAU_DETAIL_REQUEST";
export const MAU_DETAIL_SUCCESS = "MAU_DETAIL_SUCCESS";
export const MAU_DETAIL_FAIL = "MAU_DETAIL_FAIL";

export const MAU_SIZE_LIST_REQUEST = "MAU_SIZE_LIST_REQUEST";
export const MAU_SIZE_LIST_SUCESS = "MAU_SIZE_LIST_SUCESS";
export const MAU_SIZE_LIST_FAIL = "MAU_SIZE_LIST_FAIL";

export const MAU_DELETE_REQUEST = "MAU_DELETE_REQUEST";
export const MAU_DELETE_SUCCESS = "MAU_DELETE_SUCCESS";
export const MAU_DELETE_FAIL = "MAU_DELETE_FAIL";

export const MAU_CREATE_REQUEST = "MAU_CREATE_REQUEST";
export const MAU_CREATE_SUCCESS = "MAU_CREATE_SUCCESS";
export const MAU_CREATE_FAIL = "MAU_CREATE_FAIL";

export const MAU_UPDATE_REQUEST = "MAU_UPDATE_REQUEST";
export const MAU_UPDATE_SUCCESS = "MAU_UPDATE_SUCCESS";
export const MAU_UPDATE_FAIL = "MAU_UPDATE_FAIL";
