export const NGUOIDUNG_LIST_REQUEST = "NGUOIDUNG_LIST_REQUEST";
export const NGUOIDUNG_LIST_SUCCESS = "NGUOIDUNG_LIST_SUCCESS";
export const NGUOIDUNG_LIST_FAIL = "NGUOIDUNG_LIST_FAIL";

export const NGUOIDUNG_DETAIL_REQUEST = "NGUOIDUNG_DETAIL_REQUEST";
export const NGUOIDUNG_DETAIL_SUCCESS = "NGUOIDUNG_DETAIL_SUCCESS";
export const NGUOIDUNG_DETAIL_FAIL = "NGUOIDUNG_DETAIL_FAIL";

export const NGUOIDUNG_SIZE_LIST_REQUEST = "NGUOIDUNG_SIZE_LIST_REQUEST";
export const NGUOIDUNG_SIZE_LIST_SUCESS = "NGUOIDUNG_SIZE_LIST_SUCESS";
export const NGUOIDUNG_SIZE_LIST_FAIL = "NGUOIDUNG_SIZE_LIST_FAIL";

export const NGUOIDUNG_DELETE_REQUEST = "NGUOIDUNG_DELETE_REQUEST";
export const NGUOIDUNG_DELETE_SUCCESS = "NGUOIDUNG_DELETE_SUCCESS";
export const NGUOIDUNG_DELETE_FAIL = "NGUOIDUNG_DELETE_FAIL";

export const NGUOIDUNG_CREATE_REQUEST = "NGUOIDUNG_CREATE_REQUEST";
export const NGUOIDUNG_CREATE_SUCCESS = "NGUOIDUNG_CREATE_SUCCESS";
export const NGUOIDUNG_CREATE_FAIL = "NGUOIDUNG_CREATE_FAIL";

export const NGUOIDUNG_UPDATE_REQUEST = "NGUOIDUNG_UPDATE_REQUEST";
export const NGUOIDUNG_UPDATE_SUCCESS = "NGUOIDUNG_UPDATE_SUCCESS";
export const NGUOIDUNG_UPDATE_FAIL = "NGUOIDUNG_UPDATE_FAIL";

export const NGUOIDUNG_LOGIN_REQUEST = "NGUOIDUNG_LOGIN_REQUEST";
export const NGUOIDUNG_LOGIN_SUCCESS = "NGUOIDUNG_LOGIN_SUCCESS";
export const NGUOIDUNG_LOGIN_FAIL = "NGUOIDUNG_LOGIN_FAIL";
export const NGUOIDUNG_LOGOUT = "NGUOIDUNG_LOGOUT";

export const NGUOIDUNG_REGISTER_REQUEST = "NGUOIDUNG_REGISTER_REQUEST";
export const NGUOIDUNG_REGISTER_SUCCESS = "NGUOIDUNG_REGISTER_SUCCESS";
export const NGUOIDUNG_REGISTER_FAIL = "NGUOIDUNG_REGISTER_FAIL";

export const NGUOIDUNG_INFO_REQUEST = "NGUOIDUNG_INFO_REQUEST";
export const NGUOIDUNG_INFO_SUCCESS = "NGUOIDUNG_INFO_SUCCESS";
export const NGUOIDUNG_INFO_FAIL = "NGUOIDUNG_INFO_FAIL";

export const NGUOIDUNG_LOGOUT_REQUEST = "NGUOIDUNG_LOGOUT_REQUEST";
export const NGUOIDUNG_LOGOUT_SUCCESS = "NGUOIDUNG_LOGOUT_SUCCESS";
export const NGUOIDUNG_LOGOUT_FAIL = "NGUOIDUNG_LOGOUT_FAIL";
