export const NHACUNGCAP_LIST_REQUEST = "NHACUNGCAP_LIST_REQUEST";
export const NHACUNGCAP_LIST_SUCCESS = "NHACUNGCAP_LIST_SUCCESS";
export const NHACUNGCAP_LIST_FAIL = "NHACUNGCAP_LIST_FAIL";

export const NHACUNGCAP_DETAIL_REQUEST = "NHACUNGCAP_DETAIL_REQUEST";
export const NHACUNGCAP_DETAIL_SUCCESS = "NHACUNGCAP_DETAIL_SUCCESS";
export const NHACUNGCAP_DETAIL_FAIL = "NHACUNGCAP_DETAIL_FAIL";

export const NHACUNGCAP_SIZE_LIST_REQUEST = "NHACUNGCAP_SIZE_LIST_REQUEST";
export const NHACUNGCAP_SIZE_LIST_SUCESS = "NHACUNGCAP_SIZE_LIST_SUCESS";
export const NHACUNGCAP_SIZE_LIST_FAIL = "NHACUNGCAP_SIZE_LIST_FAIL";

export const NHACUNGCAP_DELETE_REQUEST = "NHACUNGCAP_DELETE_REQUEST";
export const NHACUNGCAP_DELETE_SUCCESS = "NHACUNGCAP_DELETE_SUCCESS";
export const NHACUNGCAP_DELETE_FAIL = "NHACUNGCAP_DELETE_FAIL";

export const NHACUNGCAP_CREATE_REQUEST = "NHACUNGCAP_CREATE_REQUEST";
export const NHACUNGCAP_CREATE_SUCCESS = "NHACUNGCAP_CREATE_SUCCESS";
export const NHACUNGCAP_CREATE_FAIL = "NHACUNGCAP_CREATE_FAIL";

export const NHACUNGCAP_UPDATE_REQUEST = "NHACUNGCAP_UPDATE_REQUEST";
export const NHACUNGCAP_UPDATE_SUCCESS = "NHACUNGCAP_UPDATE_SUCCESS";
export const NHACUNGCAP_UPDATE_FAIL = "NHACUNGCAP_UPDATE_FAIL";
