export const PHIEUNHAPKHO_LIST_REQUEST = "PHIEUNHAPKHO_LIST_REQUEST";
export const PHIEUNHAPKHO_LIST_SUCCESS = "PHIEUNHAPKHO_LIST_SUCCESS";
export const PHIEUNHAPKHO_LIST_FAIL = "PHIEUNHAPKHO_LIST_FAIL";

export const PHIEUNHAPKHO_DETAIL_REQUEST = "PHIEUNHAPKHO_DETAIL_REQUEST";
export const PHIEUNHAPKHO_DETAIL_SUCCESS = "PHIEUNHAPKHO_DETAIL_SUCCESS";
export const PHIEUNHAPKHO_DETAIL_FAIL = "PHIEUNHAPKHO_DETAIL_FAIL";

export const PHIEUNHAPKHO_SIZE_LIST_REQUEST = "PHIEUNHAPKHO_SIZE_LIST_REQUEST";
export const PHIEUNHAPKHO_SIZE_LIST_SUCESS = "PHIEUNHAPKHO_SIZE_LIST_SUCESS";
export const PHIEUNHAPKHO_SIZE_LIST_FAIL = "PHIEUNHAPKHO_SIZE_LIST_FAIL";

export const PHIEUNHAPKHO_DELETE_REQUEST = "PHIEUNHAPKHO_DELETE_REQUEST";
export const PHIEUNHAPKHO_DELETE_SUCCESS = "PHIEUNHAPKHO_DELETE_SUCCESS";
export const PHIEUNHAPKHO_DELETE_FAIL = "PHIEUNHAPKHO_DELETE_FAIL";

export const PHIEUNHAPKHO_CREATE_REQUEST = "PHIEUNHAPKHO_CREATE_REQUEST";
export const PHIEUNHAPKHO_CREATE_SUCCESS = "PHIEUNHAPKHO_CREATE_SUCCESS";
export const PHIEUNHAPKHO_CREATE_FAIL = "PHIEUNHAPKHO_CREATE_FAIL";

export const PHIEUNHAPKHO_UPDATE_REQUEST = "PHIEUNHAPKHO_UPDATE_REQUEST";
export const PHIEUNHAPKHO_UPDATE_SUCCESS = "PHIEUNHAPKHO_UPDATE_SUCCESS";
export const PHIEUNHAPKHO_UPDATE_FAIL = "PHIEUNHAPKHO_UPDATE_FAIL";
