export const PHIEUDATHANG_LIST_REQUEST = "PHIEUDATHANG_LIST_REQUEST";
export const PHIEUDATHANG_LIST_SUCCESS = "PHIEUDATHANG_LIST_SUCCESS";
export const PHIEUDATHANG_LIST_FAIL = "PHIEUDATHANG_LIST_FAIL";

export const PHIEUDATHANG_DETAIL_REQUEST = "PHIEUDATHANG_DETAIL_REQUEST";
export const PHIEUDATHANG_DETAIL_SUCCESS = "PHIEUDATHANG_DETAIL_SUCCESS";
export const PHIEUDATHANG_DETAIL_FAIL = "PHIEUDATHANG_DETAIL_FAIL";

export const PHIEUDATHANG_SIZE_LIST_REQUEST = "PHIEUDATHANG_SIZE_LIST_REQUEST";
export const PHIEUDATHANG_SIZE_LIST_SUCESS = "PHIEUDATHANG_SIZE_LIST_SUCESS";
export const PHIEUDATHANG_SIZE_LIST_FAIL = "PHIEUDATHANG_SIZE_LIST_FAIL";

export const PHIEUDATHANG_DELETE_REQUEST = "PHIEUDATHANG_DELETE_REQUEST";
export const PHIEUDATHANG_DELETE_SUCCESS = "PHIEUDATHANG_DELETE_SUCCESS";
export const PHIEUDATHANG_DELETE_FAIL = "PHIEUDATHANG_DELETE_FAIL";

export const PHIEUDATHANG_CREATE_REQUEST = "PHIEUDATHANG_CREATE_REQUEST";
export const PHIEUDATHANG_CREATE_SUCCESS = "PHIEUDATHANG_CREATE_SUCCESS";
export const PHIEUDATHANG_CREATE_FAIL = "PHIEUDATHANG_CREATE_FAIL";

export const PHIEUDATHANG_UPDATE_REQUEST = "PHIEUDATHANG_UPDATE_REQUEST";
export const PHIEUDATHANG_UPDATE_SUCCESS = "PHIEUDATHANG_UPDATE_SUCCESS";
export const PHIEUDATHANG_UPDATE_FAIL = "PHIEUDATHANG_UPDATE_FAIL";
