export const PHIEUBANHANG_LIST_REQUEST = "PHIEUBANHANG_LIST_REQUEST";
export const PHIEUBANHANG_LIST_SUCCESS = "PHIEUBANHANG_LIST_SUCCESS";
export const PHIEUBANHANG_LIST_FAIL = "PHIEUBANHANG_LIST_FAIL";

export const PHIEUBANHANG_DETAIL_REQUEST = "PHIEUBANHANG_DETAIL_REQUEST";
export const PHIEUBANHANG_DETAIL_SUCCESS = "PHIEUBANHANG_DETAIL_SUCCESS";
export const PHIEUBANHANG_DETAIL_FAIL = "PHIEUBANHANG_DETAIL_FAIL";

export const PHIEUBANHANG_SIZE_LIST_REQUEST = "PHIEUBANHANG_SIZE_LIST_REQUEST";
export const PHIEUBANHANG_SIZE_LIST_SUCESS = "PHIEUBANHANG_SIZE_LIST_SUCESS";
export const PHIEUBANHANG_SIZE_LIST_FAIL = "PHIEUBANHANG_SIZE_LIST_FAIL";

export const PHIEUBANHANG_DELETE_REQUEST = "PHIEUBANHANG_DELETE_REQUEST";
export const PHIEUBANHANG_DELETE_SUCCESS = "PHIEUBANHANG_DELETE_SUCCESS";
export const PHIEUBANHANG_DELETE_FAIL = "PHIEUBANHANG_DELETE_FAIL";

export const PHIEUBANHANG_CREATE_REQUEST = "PHIEUBANHANG_CREATE_REQUEST";
export const PHIEUBANHANG_CREATE_SUCCESS = "PHIEUBANHANG_CREATE_SUCCESS";
export const PHIEUBANHANG_CREATE_FAIL = "PHIEUBANHANG_CREATE_FAIL";

export const PHIEUBANHANG_UPDATE_REQUEST = "PHIEUBANHANG_UPDATE_REQUEST";
export const PHIEUBANHANG_UPDATE_SUCCESS = "PHIEUBANHANG_UPDATE_SUCCESS";
export const PHIEUBANHANG_UPDATE_FAIL = "PHIEUBANHANG_UPDATE_FAIL";
