export const PHIEUCHI_LIST_REQUEST = "PHIEUCHI_LIST_REQUEST";
export const PHIEUCHI_LIST_SUCCESS = "PHIEUCHI_LIST_SUCCESS";
export const PHIEUCHI_LIST_FAIL = "PHIEUCHI_LIST_FAIL";

export const PHIEUCHI_CREATE_REQUEST = "PHIEUCHI_CREATE_REQUEST";
export const PHIEUCHI_CREATE_SUCCESS = "PHIEUCHI_CREATE_SUCCESS";
export const PHIEUCHI_CREATE_FAIL = "PHIEUCHI_CREATE_FAIL";